language: ruby
rvm:
- 2.0.0
- 2.1.8
- 2.2.0
before_install: gem install bundler -v 1.11.2
notifications:
  slack:
    secure: G8QkCs64HRwEh5EeLACsrhIi+Sqfcq/fBVPMKmBnMQ5CMEfZruhzjNX+O2yMWWGTihItovfVqYNYU4sfMnDwPocuSU+5ksRBGHZnxy+uY4UJVJ+mJbVMxx0zJta4ncDxPecTdRxEnLjsdTPGI0cboO6XkMwxnGvJVoElk2XgFg0bw303gy0oCCBZC1oWW6Y07OWWDNdij/H9FXmyIwZXjaTNNYVfeAunrHxsZ87OpNfEGle3x6p24ggq76+aHziJ81es7Fjvs6xT+EVFy/6bbtUrC1aLMZNi6LVU+kFTVwoEB236LMCtOy6t9BdI4ccAV+OnDQ68v8n2LyazqHgQfN7IStFH32Eatv1JPz7pgnvGKlSU0f/ulOhM2CUBFJ/wptzPCfutl/Anug0o7KeNB3hm9/WvgkHl5yXFF0/kbLoOeIH7CMqYQYLncQVxJSqUCn+MNXavPbNn3v97pSwVYE8p/QbRjJBS+KQZB8MGXRWAinOz/wEBUlxYQHHrQawzjlnSANb3l5Wz/eCfMVowwUDkjqQaO/m8inCBZF9a+91fMazJyF77CukDGkW/r82wL1xPWI2wMH8gG8v7UG+AC8dI1E73UGdcdvix1gCv3xegBLE2ZmV4sTqSJEwGtuEH4f3PVT17lpB39xYuoDdV4ymgbj/hKeH3/7iwQpqrj+Q=
